### ISSUE TITLE
Make `working-directory` configurable

### ISSUE THREAD

**Issue by vbrandl** [rustsec/audit-check#14]
I have a polyglot project with a backend in rust under `./backend` and a frontend in elm. The project does not have a `Cargo.toml` or `Cargo.lock` in the project root. This causes the action to fail.

For other actions, I can overwrite the `working-directory` to fix this problem:

```yml
defaults:
  run:
    working-directory: backend
```

It would be nice to have an option for the audit action to run in a subdirectory.
