### ISSUE TITLE
Run fails on Dependabot PRs

### ISSUE THREAD

**Issue by mkroening** [rustsec/audit-check#34]
When configured as

```yaml
on:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
```

the job consistently [fails](https://github.com/hermit-os/kernel/actions/runs/12647968841/job/35241366086?pr=1545) when Dependabot creates the PR. When _I_ open a PR, the job consistently [succeeds](https://github.com/hermit-os/kernel/actions/runs/12596902061/job/35108876212?pr=1524).

I am not sure if this is related to https://github.com/rustsec/audit-check/issues/28.

Meanwhile, I will disable the check on `push`es.
